---
# This role deploys the mongod processes.
- name: create data directory for mongodb data members
  file: path={{ mongodb_datadir_prefix }}/db state=directory owner=mongod group=mongod

- name: create arbiter directory for mongodb arbiters
  file: path={{ mongodb_datadir_prefix }}/arb state=directory owner=mongod group=mongod

- name: create log directory for mongodb
  file: path=/var/log/mongodb state=directory owner=mongod group=mongod

