---
# This Playbook runs all the common plays in the deployment
- name: Add the MongoDB GPG key.
  rpm_key: state=present key=https://www.mongodb.org/static/pgp/server-3.2.asc

- name: Create the repository for 10Gen
  copy: src=10gen.repo.j2 dest=/etc/yum.repos.d/10gen.repo

- name: Create the mongod user
  user: name=mongod comment="MongoD"

- name: Create the data directory for the namenode metadata
  file: path={{ mongodb_datadir_prefix }} owner=mongod group=mongod state=directory

- name: Install the mongodb package
  yum: name={{ item }} state=installed
  with_items:
   - mongodb-org
   - mongodb-org-server
   - bc
   - python-pip
   - ntp

- name: Enable NTPD
  service: name=ntpd enabled=yes state=started

- name: Install the latest pymongo package
  pip: name=pymongo state=latest use_mirrors=no
