---
# This Playbook runs all the common plays in the deployment
- name: Create the hosts file for all machines
  template: src=hosts.j2 dest=/etc/hosts

- name: Create the repository for 10Gen
  copy: src=10gen.repo.j2 dest=/etc/yum.repos.d/10gen.repo

- name: Create the EPEL Repository.
  copy: src=epel.repo.j2 dest=/etc/yum.repos.d/epel.repo

- name: Create the GPG key for EPEL
  copy: src=RPM-GPG-KEY-EPEL-7 dest=/etc/pki/rpm-gpg

- name: Create the mongod user
  user: name=mongod comment="MongoD"

- name: Create the data directory for the namenode metadata
  file: path={{ mongodb_datadir_prefix }} owner=mongod group=mongod state=directory

- name: Install the mongodb package
  yum: name={{ item }} state=installed
  with_items:
   - libselinux-python
   - mongodb-org
   - mongodb-org-server
   - bc
   - python-pip
   - ntp

- name: Enable NTPD
  service: name=ntpd enabled=yes state=started

- name: Install the latest pymongo package
  pip: name=pymongo state=latest use_mirrors=no

# Disable transparent_hugepages
- name: Disable transparent_hugepages, create the profile directory for tuned (1/3)
  file: path=/etc/tuned/no-thp state=directory

- name: Copy the tuned.conf to the new directory (2/3)
  copy: src=tuned.conf dest=/etc/tuned/no-thp

- name: Enable the new profile
  command: tuned-adm profile no-thp
