---
# Secure replication using the secret
- name: Copy the keyfile for replicated authentication
  copy: src=secret dest={{ mongodb_datadir_prefix }}secret owner=mongod group=mongod mode=0400
  notify:
    - Restart mongodb

- name: Create the authenticated mongodb configuration file
  template: src=mongod.conf.j2 dest=/etc/mongod.conf
  notify:
    - Restart mongodb

- name: Create the file to initialize the replicaset
  template: src=repset_init.j2 dest=/tmp/repset_init.js

- name: Initialize the replication set on the primary
  shell: /usr/bin/mongo {{ groups["mongod_primary"][0] }}:{{ mongod_port }}/admin -u admin -p {{ mongo_admin_pass }} /tmp/repset_init.js
  run_once: true
  when: inventory_hostname in groups['mongod_primary']
